# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iBeaconDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iBeaconDemo
    pod 'SnapKit', '~> 5.0.0'
   

  target 'iBeaconDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iBeaconDemoUITests' do
    # Pods for testing
  end

end
